env:
  gitconfigs: "ENCRYPTED[!e918d9400219b6f7d2588a0afd4fffd3df3735cf5db059e2733e4269c363811a818e686e7b04c2b4fd671580e393f20c!]"
  credensial: "ENCRYPTED[!6f130d1ac4acaf8c4a50f4ce8c5a9cefe2ad5e2fd511e0d25c3ca5d15f6f15977184c846ce5cee54bb6019a060648fed!]"
  tokentl: "ENCRYPTED[!48df36a023301be77fca5928aee9d9aa41d168a17b49a1379dcdd2544d897abdd71244a71b29f810411fefc8404625d2!]"
  idtl: "ENCRYPTED[!a12665bdcb530d0f6222ec4f353356c9819303c6a85209c78bd9c1f2d57b16912c9b96d60e567367846f2438f9f75967!]"
  rcloneconfig: "ENCRYPTED[!6cd17859df5b240b807fab881bdae9e268476b6c78f625fd52499ddb949a949affc30b88bdfbe29c1866e3812c9998a2!]"
  rclonedir: "me:rom"
  rclonefile: "ccache-losqO3.tar.gz"

task:
  name: "Build"
  timeout_in: 120m
  container:
    image: thisfor/ubuntu:latest
    cpu: 8
    memory: 32G
    greedy: true

  setup_script:
    - tle -t "${CIRRUS_COMMIT_MESSAGE} ( <a href='https://cirrus-ci.com/task/${CIRRUS_TASK_ID}'>$CIRRUS_BRANCH</a> )"
    - echo "$credensial" > ~/.git-credentials
    - echo "$gitconfigs" > ~/.gitconfig
    - echo "$rcloneconfig" > ~/.rclone.conf
    - ./main.sh copy_cache

  sync_script: ./main.sh sync
  build_script: ./main.sh build
  upload_script: ./main.sh upload

  on_failure:
    notiferror_script:
      - tle -t "Build Failed!"
      - tle -f "${PWD}/android/out/error.log"